events {
    worker_connections 1024;
}

http {
    # Маршрутизация запросов по Bounded Contexts
    server {
        listen 80;

        # Всё что касается подачи и чтения жалоб идет в Complaint Service
        location /api/complaints/ {
            proxy_pass http://complaint-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Всё что касается работы модераторов (ревью) идет в Moderation Service
        location /api/moderation/ {
            proxy_pass http://moderation-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}